name: Fetch Weather Data

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow automatically every day at midnight UTC
  schedule:
    - cron: '50 5 * * *' # Runs daily at 00:00 UTC

jobs:
  fetch_and_commit_weather:
    runs-on: ubuntu-latest
    permissions:
      # Need write permissions to commit code back to the repository
      contents: write
    steps:
      - name: Checkout repository
        # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it
        uses: actions/checkout@v4

      - name: Fetch weather data
        # Use curl to make the GET request and save the output directly to a file
        # -s: Silent mode (don't show progress)
        # -L: Follow redirects
        # -o: Output file name
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          API_URL="https://api.open-meteo.com/v1/forecast?latitude=31.2222&longitude=121.4581&hourly=temperature_2m&timezone=auto"
          OUTPUT_FILE="weather_data.json"
          echo "Fetching weather data from $API_URL"
          curl -sL "$API_URL" -o "$OUTPUT_FILE"
          echo "Weather data saved to $OUTPUT_FILE"
          # Optional: Add a small delay in case the API has rate limits or eventual consistency
          # sleep 5

      - name: Commit and push if data changed
        # Configure git user
        # Check if the output file has changes compared to the last commit
        # If yes, add, commit, and push the file
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          OUTPUT_FILE="weather_data.json"

          # Check git status. If there are no changes to the file, exit gracefully.
          
          fi

          # If there are changes, add, commit, and push
          echo "Changes detected in $OUTPUT_FILE. Committing..."
          git add "$OUTPUT_FILE"
          # Use date command to include the update time in the commit message
          git commit -m "Update weather data for Shanghai - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push
